/** Known Google Sheet sources for IIMK PGP29/FIN06/LSM06 (2025-27). */
export const IIMK_SHEET_REGISTRY = [
  {
    label: "PGP-29 Term I",
    spreadsheetId: "1t__BBBDc3TWHx9Jbhv1vEjBYxKA78c295AhhxL5fr4g",
    scheduleGid: "0",
    courseDetailsGid: "1164249433",
    kind: "PER_PROGRAM" as const,
    batchLabel: "PGP29",
    termNumber: 1,
    programFilter: null,
  },
  {
    label: "FIN-06 Term I",
    spreadsheetId: "15ysVIFru4xoYdbek9Pr3pwLSzb67VV2YKnWT77pso-k",
    scheduleGid: "0",
    courseDetailsGid: "1035626201",
    kind: "PER_PROGRAM" as const,
    batchLabel: "FIN06",
    termNumber: 1,
    programFilter: null,
  },
  {
    label: "LSM-06 Term I",
    spreadsheetId: "1Iyt9KNIO6_gPipmbT79TDVdsOxyOIcVl2Eu-jhibo_A",
    scheduleGid: "0",
    courseDetailsGid: "1025281615",
    kind: "PER_PROGRAM" as const,
    batchLabel: "LSM06",
    termNumber: 1,
    programFilter: null,
  },
  {
    label: "PGP-29 Term II",
    spreadsheetId: "1RoyKFfA20rZT3O-vfGI9OOpS53X5EkTj2M5gFdvOMCk",
    scheduleGid: "0",
    courseDetailsGid: "688339414",
    kind: "PER_PROGRAM" as const,
    batchLabel: "PGP29",
    termNumber: 2,
    programFilter: null,
  },
  {
    label: "FIN-06 Term II",
    spreadsheetId: "1dew5n8WtPdwffrbPVKeAYqEpRu8ajTjGa6xRsHfuIDg",
    scheduleGid: "0",
    courseDetailsGid: "126049116",
    kind: "PER_PROGRAM" as const,
    batchLabel: "FIN06",
    termNumber: 2,
    programFilter: null,
  },
  {
    label: "LSM-06 Term II",
    spreadsheetId: "1AXziFwOCt6C_fEkEVPlPJ6WfQqcyAY-66HUaYEtydYY",
    scheduleGid: "0",
    courseDetailsGid: "24617776",
    kind: "PER_PROGRAM" as const,
    batchLabel: "LSM06",
    termNumber: 2,
    programFilter: null,
  },
  {
    label: "PGP-29 Term III",
    spreadsheetId: "15yrTywIp6s-64fBpghqdSpW2rqVQpJYStVSEIpTn0_I",
    scheduleGid: "0",
    courseDetailsGid: "48532715",
    kind: "PER_PROGRAM" as const,
    batchLabel: "PGP29",
    termNumber: 3,
    programFilter: null,
  },
  {
    label: "FIN-06 Term III",
    spreadsheetId: "1rgNHxqgLXNJ7asHl9h245IuKwL7eCN17m_LEcNDFgeg",
    scheduleGid: "1408440285",
    courseDetailsGid: "1598078777",
    kind: "PER_PROGRAM" as const,
    batchLabel: "FIN06",
    termNumber: 3,
    programFilter: null,
  },
  {
    label: "LSM-06 Term III",
    spreadsheetId: "1qIpPyD9hWUgKa9ClhsNTnktWqtpRaNrvRyx-wryuxbM",
    scheduleGid: "279712602",
    courseDetailsGid: "1222779121",
    kind: "PER_PROGRAM" as const,
    batchLabel: "LSM06",
    termNumber: 3,
    programFilter: null,
  },
  {
    label: "PGP29/FIN06/LSM06 Term IV (combined)",
    spreadsheetId: "13-v2m0g3dr3UVo09i3qHLsMqZRyy_6zXf21AtDUtSOQ",
    scheduleGid: "0",
    courseDetailsGid: "302639785",
    kind: "COMBINED" as const,
    batchLabel: null,
    termNumber: 4,
    programFilter: null,
    /** Combined sheet links to all three batches' Term IV. */
    combinedBatches: ["PGP29", "FIN06", "LSM06"] as const,
    combinedProgramFilters: ["PGP29", "FIN06", "LSM06"] as const,
  },
] as const;

export type SheetRegistryEntry = (typeof IIMK_SHEET_REGISTRY)[number];
